import { ar_Sa_mention, az_Latn_AZ_mention, bg_BG_mention, ca_ES_mention, ca_Es_VALENCIA_mention, cs_CZ_mention, 
    cy_GB_mention, da_DK_mention, de_DE_mention, el_GR_mention, en_GB_mention, en_US_mention, es_ES_mention, 
    es_MX_mention, et_EE_mention, eu_ES_mention, fi_FI_mention, fil_PH_mention, fr_CA_mention, fr_FR_mention, 
    gl_ES_mention, he_IL_mention, hi_IN_mention, hr_HR_mention, hu_HU_mention, id_ID_mention, is_IS_mention, 
    it_IT_mention, ja_JP_mention, ka_GE_mention, kk_KZ_mention, ko_KR_mention, lt_LT_mention, lv_LV_mention, 
    mk_MK_mention, nb_NO_mention, nl_NL_mention, nn_NO_mention, pl_PL_mention, pt_BR_mention, pt_PT_mention, 
    ro_RO_mention, ru_RU_mention, sk_SK_mention, sl_SI_mention, sq_AL_mention, sr_Latn_RS_mention, sv_SE_mention, 
    th_TH_mention, tr_TR_mention, uk_UA_mention, vi_VN_mention, zh_CN_mention, zh_TW_mention } from "./locale strings";

export const localeMap: Record<string, string> = {
    ar_SA: ar_Sa_mention,
    az_Latn_AZ: az_Latn_AZ_mention,
    bg_BG: bg_BG_mention, 
    ca_ES: ca_ES_mention,
    ca_Es_VALENCIA: ca_Es_VALENCIA_mention, 
    cs_CZ: cs_CZ_mention, 
    cy_GB: cy_GB_mention, 
    da_DK: da_DK_mention,
    de_DE: de_DE_mention, 
    el_GR: el_GR_mention, 
    en_GB: en_GB_mention, 
    en_US: en_US_mention,
    es_ES: es_ES_mention, 
    es_MX: es_MX_mention,
    et_EE: et_EE_mention, 
    eu_ES: eu_ES_mention, 
    fi_FI: fi_FI_mention, 
    fil_PH: fil_PH_mention, 
    fr_CA: fr_CA_mention, 
    fr_FR: fr_FR_mention, 
    gl_ES: gl_ES_mention, 
    he_IL: he_IL_mention, 
    hi_IN: hi_IN_mention, 
    hr_HR: hr_HR_mention, 
    hu_HU: hu_HU_mention, 
    id_ID: id_ID_mention, 
    is_IS: is_IS_mention, 
    it_IT: it_IT_mention, 
    ja_JP: ja_JP_mention, 
    ka_GE: ka_GE_mention, 
    kk_KZ: kk_KZ_mention, 
    ko_KR: ko_KR_mention, 
    lt_LT: lt_LT_mention, 
    lv_LV: lv_LV_mention, 
    mk_MK: mk_MK_mention, 
    nb_NO: nb_NO_mention, 
    nl_NL: nl_NL_mention, 
    nn_NO: nn_NO_mention, 
    pl_PL: pl_PL_mention, 
    pt_BR: pt_BR_mention, 
    pt_PT: pt_PT_mention, 
    ro_RO: ro_RO_mention, 
    ru_RU: ru_RU_mention, 
    sk_SK: sk_SK_mention, 
    sl_SI: sl_SI_mention, 
    sq_AL: sq_AL_mention, 
    sr_Latn_RS: sr_Latn_RS_mention, 
    sv_SE: sv_SE_mention, 
    th_TH: th_TH_mention, 
    tr_TR: tr_TR_mention, 
    uk_UA: uk_UA_mention, 
    vi_VN: vi_VN_mention, 
    zh_CN: zh_CN_mention, 
    zh_TW: zh_TW_mention
}